# Generated by Django 5.0.1 on 2024-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_aboutvideo_causeofcomplaint_commentsaboutcourse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NPVideoCourse',
            new_name='VideoDetail',
        ),
    ]
