# Generated by Django 5.0.1 on 2024-01-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_npvideocourse_videodetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='number_of_videous',
            new_name='number_of_videos',
        ),
    ]
